# Use the official Elasticsearch image
FROM docker.elastic.co/elasticsearch/elasticsearch:7.17.28

# Set environment variables
ENV discovery.type=single-node

# Expose necessary ports
EXPOSE 9299 9399

