version: '3.8'

services:
  es-app:
    image: 23110281/elasticsearch:latest
    container_name: es-app
    networks:
      - backend-network
    ports:
      - "127.0.0.1:9200:9567"
      - "127.0.0.1:9300:9399"
    environment:
      - discovery.type=single-node
      - "http.port=9567"
    restart: unless-stopped
    volumes:
      - /home/23110281/assignment8/vm2/elasticsearch/data:/usr/share/elasticsearch/data

  backend:
    image: 23110281/fastapi:2
    container_name: backend
    networks:
      - backend-network
    ports:
      - "9567:9567"
    depends_on:
      - es-app
    restart: unless-stopped

networks:
  backend-network:
    driver: bridge

