version: '3.8'

services:
  backend:
    build: ./backend
    networks:
      - es_net
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - es_net
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local

networks:
  es_net:
    driver: bridge
