version: "3.8"

services:
    frontend:
        build: ./frontend
        ports:
            - "9567:9567" # Expose frontend
        environment:
            - BACKEND_URL=http://34.47.145.245:9567 # Connect frontend to backend

